/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xmlutil.variant.resolution.failure

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
